CREATE TABLE TB_TUNNELLING_SYS_THEME (
TUNNLLING_GROUP_I_D NVARCHAR(255) NULL ,--所属掘进队伍
REALITY_TUNNLLING NVARCHAR(255) NULL ,--实际掘进
PLAN_TUNNLLING NVARCHAR(255) NULL ,--计划掘进
TUNNLLING_DATE NVARCHAR(255) NULL ,--掘进日期

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)