CREATE TABLE TB_A_THREE_ANTI_SYS_THEME (
WIND NVARCHAR(255) NULL ,--巷道及重点部位的风速
GAS_DENSITY NVARCHAR(255) NULL ,--瓦斯浓度
DATE NVARCHAR(255) NULL ,--DATE
AREA_ID NVARCHAR(255) NULL ,--所属区域

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)