CREATE TABLE TB_COAL_MINING_SYS_THEME (
REALITY_OUTPUT NVARCHAR(255) NULL ,--实际产量
PLAN_OUTPUT NVARCHAR(255) NULL ,--计划产量
MINE_DATE NVARCHAR(255) NULL ,--开采日期
WORKING_FACE_ID NVARCHAR(255) NULL ,--所属工作面

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)