CREATE TABLE TB_ELECT (
XM NVARCHAR(255) NULL ,--项目
XM_TYPE NVARCHAR(255) NULL ,--xmType
DL NVARCHAR(255) NULL ,--电量（万千瓦时）
DF NVARCHAR(255) NULL ,--电费（万元）
DH NVARCHAR(255) NULL ,--单耗（千瓦时/吨）
DMDF NVARCHAR(255) NULL ,--吨煤电费（元/吨）
FGB NVARCHAR(255) NULL ,--峰谷比
JHDJ NVARCHAR(255) NULL ,--计划电价（元/千瓦时）
YSRQ NVARCHAR(255) NULL ,--预算日期

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)