CREATE TABLE TB_DAILY_STATUS (
TIME NVARCHAR(255) NULL ,--时间
ADDRESS NVARCHAR(255) NULL ,--地点
SPEAKER NVARCHAR(255) NULL ,--谈话人
BE_SPEAKER NVARCHAR(255) NULL ,--被谈话人
PERSON_TYPE NVARCHAR(255) NULL ,--不放心人员类型
TALK_REASON NVARCHAR(255) NULL ,--谈话事由
CONVERSATION NVARCHAR(255) NULL ,--谈话内容
EFFECT NVARCHAR(255) NULL ,--谈话效果

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)