CREATE TABLE TB_HAZHARDS_TAILINGSPOND (
QYMC NVARCHAR(255) NULL ,--企业名称
ZYFZR NVARCHAR(255) NULL ,--主要负责人
XXDZ NVARCHAR(255) NULL ,--详细地址
LXDH NVARCHAR(255) NULL ,--联系电话
SJZG NVARCHAR(255) NULL ,--上级主管
YZBM NVARCHAR(255) NULL ,--邮政编码
JCRQ NVARCHAR(255) NULL ,--建长日期
CYRS NVARCHAR(255) NULL ,--从业人数
JJLX NVARCHAR(255) NULL ,--经济类型
KZ NVARCHAR(255) NULL ,--矿种
KDZC NVARCHAR(255) NULL ,--固定资产（万元）
NLR NVARCHAR(255) NULL ,--年利润（万元）
WKKMC NVARCHAR(255) NULL ,--尾矿库名称
DLWZ NVARCHAR(255) NULL ,--地理位置
WKKXS NVARCHAR(255) NULL ,--尾矿库型式
WKKXSQT NVARCHAR(255) NULL ,--尾矿库型式  其它
WKKDB NVARCHAR(255) NULL ,--尾矿库等别
QKR NVARCHAR(255) NULL ,--全库容（万m³）
BG NVARCHAR(255) NULL ,--坝高（m）
SJZKR NVARCHAR(255) NULL ,--设计总库容（万m³）
SJZBG NVARCHAR(255) NULL ,--设计总坝高
BC NVARCHAR(255) NULL ,--坝长（m）
ZXGTCD NVARCHAR(255) NULL ,--最小干滩度（m）
CJGTPJPD NVARCHAR(255) NULL ,--沉积干滩平均坡度（m）
WKKWHCDFL NVARCHAR(255) NULL ,--尾矿库危害程度分类
WKKAQDFL NVARCHAR(255) NULL ,--尾矿库安全度分类
SFYZWH NVARCHAR(255) NULL ,--如果尾矿库失事是否会使下游重要城镇、工矿企业、重要铁路干线遭受严重灾害
JBLD NVARCHAR(255) NULL ,--坝址区地震基本烈度
YWHPT NVARCHAR(255) NULL ,--库区有无滑坡体
YWNSL NVARCHAR(255) NULL ,--库区有无产生泥石流的条件
FYDQ NVARCHAR(255) NULL ,--库区是否处于岩溶或裂隙发育地区
YWLF NVARCHAR(255) NULL ,--库区有无滥伐、滥垦、滥牧现象
BX NVARCHAR(255) NULL ,--坝型
CQBG NVARCHAR(255) NULL ,--坝高（m）
CQBC NVARCHAR(255) NULL ,--坝长（m）
DBFF NVARCHAR(255) NULL ,--堆坝方法
DG NVARCHAR(255) NULL ,--堆高（m）
WKFJSBXH NVARCHAR(255) NULL ,--尾矿分级设备型号
SL NVARCHAR(255) NULL ,--数量
HSMJ NVARCHAR(255) NULL ,--汇水面积（km²）
CQ NVARCHAR(255) NULL ,--初期（年）
ZHQ NVARCHAR(255) NULL ,--中、后期（年）
WKBAQCG NVARCHAR(255) NULL ,--尾矿坝安全超高
WKKDHKR NVARCHAR(255) NULL ,--尾矿库调洪库容（万m³）
PHXTDXS NVARCHAR(255) NULL ,--排洪系统的型式
WKLD NVARCHAR(255) NULL ,--尾矿粒度d（mm）
WKBZ NVARCHAR(255) NULL ,--尾矿比重	（t/m3）
WKKDGCXM NVARCHAR(255) NULL ,--尾矿坝的观测项目
WKKGS NVARCHAR(4000) NULL ,--尾矿库的尾矿浓缩分级、放矿筑坝、回水排水、防汛渡汛、抗震等工作概述
WKXKBKGS NVARCHAR(4000) NULL ,--如果是危库、险库或病库,对危险情况作出概述
JJFF NVARCHAR(4000) NULL ,--尾矿库曾出现的问题及采取的解决办法
BZ NVARCHAR(4000) NULL ,--备注
TBR NVARCHAR(255) NULL ,--填表人
TBRLXDH NVARCHAR(255) NULL ,--填表人联系电话
TBRQ NVARCHAR(255) NULL ,--填表日期

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)