CREATE TABLE TB_TANK_HAZARDS (
MATERIALS_ID VARCHAR(50) NULL,--危险物质ID
TANK_NUMBER NVARCHAR(255) NULL ,--贮罐序号
TANK_ARAE_I_D NVARCHAR(255) NULL ,--贮罐区ID
TANK_NAME NVARCHAR(255) NULL ,--贮罐名称
TANK_FORM NVARCHAR(255) NULL ,--贮罐形状
TANK_SHAPE NVARCHAR(255) NULL ,--贮罐形式
INSTALL_SHAPE NVARCHAR(255) NULL ,--安装形式
TANK_MATERIAL NVARCHAR(255) NULL ,--贮罐材质
NOMINAL_DIAMETER NVARCHAR(255) NULL ,--公称直径
VOLUME NVARCHAR(255) NULL ,--容积
KEEP_MATTER_NAME NVARCHAR(255) NULL ,--贮存物质名称
MATTER_STATE NVARCHAR(255) NULL ,--物质状态
MAX_KEEP NVARCHAR(255) NULL ,--日常最大贮存量
DESIGN_ABLITY NVARCHAR(255) NULL ,--设计能力
REAL_ABLITY NVARCHAR(255) NULL ,--实际工作压力
DESIGN_TEMPERATURE NVARCHAR(255) NULL ,--设计温度
REAL_TEMPERATURE NVARCHAR(255) NULL ,--实际工作温度
DESIGNED_SERVICE_LIFE NVARCHAR(255) NULL ,--设计使用年限
OPERATION_DATE NVARCHAR(255) NULL ,--投产时间
FEEDING_MODE NVARCHAR(255) NULL ,--进料方式
DISCHARGING_MODE NVARCHAR(255) NULL ,--出料方式
FEEDING_DIAMETER NVARCHAR(255) NULL ,--进料管道直径
FEEDING_DESIGN_ABLITY NVARCHAR(255) NULL ,--进料管道设计压力
FEEDING_REAL_ABLITY NVARCHAR(255) NULL ,--进料管道实际工作压力
DISCHARGIN_DIAMETER NVARCHAR(255) NULL ,--出料管道直径
DISCHARGIN_DESIGN_ABLITY NVARCHAR(255) NULL ,--出料管道设计压力
DISCHARGIN_REAL_ABLITY NVARCHAR(255) NULL ,--出料管道实际工作压力

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)