CREATE TABLE TB_TRAN (
WORK_FACE NVARCHAR(255) NULL ,--工作面
STATISTICAL_TIME NVARCHAR(255) NULL ,--统计时间
TURNS NVARCHAR(255) NULL ,--无故障运行天数
WORK_FACE_BY_NAME NVARCHAR(255) NULL ,--workFaceByName

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)