CREATE TABLE TB_QUESTION_CREDIT (
QS_TYPE_ID NVARCHAR(255) NULL ,--题目类型Id
QS_NAME NVARCHAR(255) NULL ,--题目问题
OPTION_A NVARCHAR(255) NULL ,--题目选项A
OPTION_B NVARCHAR(255) NULL ,--题目选项A
OPTION_C NVARCHAR(255) NULL ,--题目选项A
OPTION_D NVARCHAR(255) NULL ,--题目选项A
OPTION_F NVARCHAR(255) NULL ,--题目选项A
QS_ANSWER NVARCHAR(255) NULL ,--题目答案
QS_USER NVARCHAR(255) NULL ,--命卷人
REMARKS NVARCHAR(255) NULL ,--备注
QUARTERS_TYPE_ID NVARCHAR(255) NULL,--岗位类型

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)