CREATE TABLE TB_EMPLOYEE (
JOB_NUM NVARCHAR(255) NULL ,--员工号
NAME NVARCHAR(255) NULL ,--员工姓名
MAJOR NVARCHAR(255) NULL ,--专业
POST NVARCHAR(255) NULL ,--岗位

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)