CREATE TABLE TB_MACHINE_ELECTRIC_SYS_THEME (
INTACT_RATE NVARCHAR(255) NULL ,--设备完好率
OVERHAUL_CONDITION NVARCHAR(255) NULL ,--检修情况
DEPARTMENT_ID NVARCHAR(255) NULL ,--所属部门
OVERHAU_DATE NVARCHAR(255) NULL ,--检修日期

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)