CREATE TABLE TB_ESSENTIALS (
CZYL NVARCHAR(255) NULL ,--一、岗标操作要领
KSYD NVARCHAR(255) NULL ,--二、手指口述要点
SGAL NVARCHAR(255) NULL ,--三、典型事故案例
SSZY NVARCHAR(255) NULL ,--所属专业
SSGZ NVARCHAR(255) NULL ,--所属工种

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)