CREATE TABLE TB_DEPLOY (
BLOOD_PRESSURE_LOW NVARCHAR(255) NULL ,--血压-低
BLOOD_PRESSURE_HIGH NVARCHAR(255) NULL ,--血压-高
PULSE_RATE NVARCHAR(255) NULL ,--脉率
ELECTROCARDIOGRAM NVARCHAR(255) NULL ,--心电图
BC NVARCHAR(255) NULL ,--B超
PNEUMOCONIOSIS NVARCHAR(255) NULL ,--尘肺病
BLOOD_EXAMINATION NVARCHAR(255) NULL ,--血液检查
LK_EXAMINATION NVARCHAR(255) NULL ,--肝肾功能
NERVOUS_SYSTEM NVARCHAR(255) NULL ,--神经系统
THYROID NVARCHAR(255) NULL ,--甲状腺
SUPERFICIAL_LYMPHADENOPATHY NVARCHAR(255) NULL ,--浅表淋巴结
SKIN_AND_MUCOSA NVARCHAR(255) NULL ,--皮肤黏膜

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)