CREATE TABLE TB_HAZARDS_RESULT (
HAZARDS_ID VARCHAR(50) NULL ,--危险源Id
INFO NVARCHAR(255) NULL ,--辨识信息
REASON NVARCHAR(255) NULL ,--辨识原因

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL,
CONSTRAINT [UNI_RESULT_HAZARDS_ID] UNIQUE ([HAZARDS_ID] ASC)
)