--危险源的总视图
ALTER VIEW VIEW_HAZARDS AS 
SELECT t.*,TB_ENTERPRISE.CORP_NAME,ISNULL(TB_HAZARDS_RESULT.INFO, '未辨识') AS INFO,TB_HAZARDS_RESULT.REASON AS REASON FROM
(
SELECT ID,BOILER_NAME as NAME,DWDM,'锅炉' as TYPE,'Boiler' as NAME_SPACE FROM TB_BOILER WHERE STATUS = '1'
UNION
SELECT ID,TANK_NAME,DWDM,'贮罐区','TankAraeHazards' FROM TB_TANK_ARAE_HAZARDS WHERE STATUS = '1'
UNION
SELECT ID,NAME,DWDM,'压力容器','PressureVesselHazards' FROM TB_PRESSURE_VESSEL_HAZARDS WHERE STATUS = '1'
UNION
SELECT ID,GDMC,DWDM,'压力管道','TbHazhardsPenstock' FROM TB_HAZHARDS_PENSTOCK WHERE STATUS = '1'
UNION
SELECT ID,DYMC,DWDM,'生产场所','TbHazhardsWorkplace' FROM TB_HAZHARDS_WORKPLACE WHERE STATUS = '1'
UNION
SELECT ID,NAME,DWDM,'库区','ReservoirAreaHazards' FROM TB_RESERVOIR_AREA_HAZARDS WHERE STATUS = '1'
UNION
SELECT ID,NAME,DWDM,'煤矿','CollieryHazards' FROM TB_COLLIERY_HAZARDS WHERE STATUS = '1'
UNION
SELECT ID,WKKMC,QYMC,'尾矿库','HazhardsTailingspond' FROM TB_HAZHARDS_TAILINGSPOND WHERE STATUS = '1'
UNION
SELECT ID,MINE_NAME,DWDM,'金属非金属地下矿山','MinesHazards' FROM TB_MINES_HAZARDS WHERE STATUS = '1'
UNION
SELECT ID,dangerplacename,DWDM,'危险场所','dangerplace' FROM TB_DANGEROUSPLACE WHERE STATUS = '1'
) t
LEFT JOIN
TB_ENTERPRISE
ON t.DWDM = TB_ENTERPRISE.ID
LEFT JOIN
TB_HAZARDS_RESULT
ON TB_HAZARDS_RESULT.HAZARDS_ID = t.ID
GO