CREATE TABLE TB_WORK_FACE (
NUMBER NVARCHAR(255) NULL ,--工作面编号
WORK_FACE_NAME NVARCHAR(255) NULL ,--工作面名称
WORK_FACE_PLACE NVARCHAR(MAX) NULL ,--工作面位置
WORK_FACE_CASE NVARCHAR(MAX) NULL ,--工作面情况
DANGEROUS NVARCHAR(255) NULL ,--危险源
LOSS NVARCHAR(MAX) NULL ,--可能造成的伤害和损失
STEP NVARCHAR(MAX) NULL ,--当事人应该采取的措施
BZ NVARCHAR(255) NULL ,--备注

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)