CREATE TABLE TB_HIDDEN_DANGERS (
FIND_PEOPLE__ID NVARCHAR(255) NULL ,--发现人ID
FIND_PEOPLE__NAME NVARCHAR(255) NULL ,--发现人姓名
FIND_PEOPLE__DEPARTMENT NVARCHAR(255) NULL ,--发现人部门
FIND_PEOPLE__POSITION NVARCHAR(255) NULL ,--发现人职务
DISCOVERY_TIME NVARCHAR(255) NULL ,--发现时间
LOCATION NVARCHAR(255) NULL ,--地点
SPECIALTY NVARCHAR(255) NULL ,--专业
CHECK_LINE NVARCHAR(255) NULL ,--检查线路
CHECK_LOCATION NVARCHAR(255) NULL ,--检查地点
CHECK_ITEM NVARCHAR(255) NULL ,--检查项目
CHECK_LABEL NVARCHAR(255) NULL ,--检查标准
HIDDEN_CONTENT NVARCHAR(255) NULL ,--隐患内容
HIDDEN_TYPE NVARCHAR(255) NULL ,--隐患类型
THREE_COLOR_FORM NVARCHAR(255) NULL ,--三色单
MEASURE NVARCHAR(255) NULL ,--整改措施
CORRECTIVE_PEOPLE NVARCHAR(255) NULL ,--整改人
CORRECTIVE_PEOPLE_UNITS NVARCHAR(255) NULL ,--整改人单位
CORRECTIVE_PEOPLE_NAME NVARCHAR(255) NULL ,--整改人姓名
DEADLINE NVARCHAR(255) NULL ,--整改期限
CORRECTION_REPORT NVARCHAR(255) NULL ,--整改结果
COMPLETION_TIME NVARCHAR(255) NULL ,--完成时间
FOLLOW_UP NVARCHAR(255) NULL ,--跟踪落实

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)